# This is a basic workflow to help you get started with Actions

name: CopilotJob

on:
  workflow_dispatch:

permissions: 
  issues: write

jobs:
  copilot-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.0

      - name: Install GitHub Copilot CLI
        run: npm install -g @github/copilot

      - name: Generate certificate report
        run: |
          go install github.com/jlucaspains/sharp-cert-manager/cmd/sharp-cert-manager@latest
          sharp-cert-manager check --url https://expired.badssl.com/ > cert_report.txt

      - name: Run Copilot CLI command
        run: |
          copilot -p "Analyze the contents of @cert_report.txt it contains a list of certificate statuses. If any certificate have warnings or errors, detail the issue so I can create a GitHub issue manually. Do not provide reasoning or summary, just the body text of the issue." > cert_reviewed_summary.txt
        env:
          COPILOT_GITHUB_TOKEN: ${{ secrets.COPILOT_GITHUB_TOKEN }}

      - name: Create Issue with Summary
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: "Certificate Check Summary"
          content-filepath: cert_reviewed_summary.txt
